version: '2'
services:
  app:
    image: 'telegrammessenger/proxy:1.3'
    container_name: 'mtproto-proxy'
    ports:
      - '1089:443'
    volumes:
      - './proxy-config:/data'
    restart: 'always'
    environment:
      - SECRET_COUNT=1
      - WORKERS=4
      - SECRET={{ secret }}
      - TAG={{ tag }}
