---
wireguard_port: "5888"
wireguard_path: "/etc/wireguard"

wireguard_network_name: "private"

debian_enable_testing: true
debian_pin_packages: true

generate_client_config: false
client_wireguard_path: "~/wg.conf"
