---
- name: Add wireguard ppa (Ubuntu)
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
  when:
    - ansible_distribution == "Ubuntu"

- name: Install linux headers (Ubuntu)
  apt:
    update_cache: yes
    state: present
    name: linux-headers-generic
  when:
    - ansible_distribution == "Ubuntu"

- name: Add unstable repository (Debian)
  copy:
    src: templates/unstable.list
    dest: /etc/apt/sources.list.d/unstable.list
  when:
    - ansible_distribution == "Debian" and debian_enable_testing

- name: Pin packages (Debian)
  copy:
    src: templates/limit-unstable
    dest: /etc/apt/preferences.d/limit-unstable
  when:
    - ansible_distribution == "Debian" and debian_pin_packages

- name: Get kernel version (Debian)
  command: uname -r
  register: kernel
  when:
    - ansible_distribution == "Debian"

- name: Install kernel headers (Debian)
  apt:
    state: present
    update_cache: true
    name: linux-headers-{{ kernel.stdout }}
  when:
    - ansible_distribution == "Debian"

- name: Install wireguard
  apt:
    update_cache: yes
    state: present
    name: wireguard

- name: Read private key
  stat:
    path: "{{ wireguard_path }}/privatekey"
  register: privatekey

- name: Generate wireguard keys
  shell: "umask 077; wg genkey | tee {{ wireguard_path  }}/privatekey | wg pubkey > {{ wireguard_path }}/publickey"
  when: not privatekey.stat.exists

- name: Read private key
  slurp:
    src: "{{ wireguard_path }}/privatekey"
  register: private

- name: Read public key
  slurp:
    src: "{{ wireguard_path }}/publickey"
  register: public

- name: Generate configs
  template:
    src: interface.conf.j2
    dest: "{{ wireguard_path }}/{{ wireguard_network_name }}.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o="
  register: config

- name: Start and enable wg-quick systemd service
  systemd:
    name: "wg-quick@{{ wireguard_network_name }}"
    enabled: yes
    state: started

- name: Restart wg-quick service if required
  systemd:
    name: "wg-quick@{{ wireguard_network_name }}"
    state: restarted
  when: config.changed
