---
- name: Install necessary admin packages
  become: true
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - tmux
      - mosh
  when: ansible_os_family != "Darwin"

- name: Copy .local configs
  copy:
    src: home/
    dest: "{{ ansible_user_dir }}/"
  notify: reload_console
  tags: copy_configs
