---
- name: Templating docker-compose.yml
  template:
    src: 'docker-compose.yml'
    dest: '/home/{{ ansible_env.SUDO_USER }}/mtproto-proxy/docker-compose.yml'

- name: Run docker-compose up
  docker_service:
    project_src: '/home/{{ ansible_env.SUDO_USER }}/mtproto-proxy'
