galaxy_info:
  role_name: wireguard-private-networking
  author: mawalu
  company: student
  description: Build your own multi server private network using wireguard and ansible
  issue_tracker_url: https://github.com/mawalu/wireguard-private-networking/issues
  license: MIT
  min_ansible_version: 2.7
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
  - wireguard
  - vpn
  - networking

dependencies: []
